version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sismico_db
      POSTGRES_USER: sismico_user
      POSTGRES_PASSWORD: sismico_password