# Generated by Django 5.0.1 on 2024-04-11 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('magnitude', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('mag_type', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('url', models.CharField(max_length=255)),
                ('tsunami', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
            ],
        ),
    ]
